# Generated by Django 3.2.18 on 2023-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitems',
            name='resturant_price',
        ),
        migrations.AddField(
            model_name='listitems',
            name='resturant_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listitems',
            name='resturant_distance',
            field=models.DecimalField(decimal_places=15, max_digits=16),
        ),
        migrations.AlterField(
            model_name='listitems',
            name='resturant_rating',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='listitems',
            name='user_rating',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
