# Generated by Django 3.2.18 on 2023-05-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0002_auto_20230504_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='resturant_distance',
            field=models.DecimalField(decimal_places=13, max_digits=17),
        ),
        migrations.AlterField(
            model_name='listitems',
            name='resturant_rating',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='listitems',
            name='resturant_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listitems',
            name='user_rating',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
