# Generated by Django 3.2.18 on 2023-05-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0003_auto_20230504_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitems',
            name='resturant_name',
            field=models.CharField(default='fish n chips', max_length=500),
        ),
    ]
